image: python:3.9

cache:
  paths:
    - ~/.cache/pip
    - ~/.platformio/.cache

stages:
 - deploy

before_script:
  - "pip install -U platformio"

job:
  rules:
    - if: $CI_COMMIT_TAG
  stage: deploy
  environment: production
  script:
    - pio run
  artifacts:
    name: "$CI_COMMIT_TAG"
    paths:
      - ".pio/build/"
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
deploy_production:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
